export const SHOW_HIDE_CART = "SHOW_HIDE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const UPDATE_QUANTITY="UPDATE_QUANTITY";
export const DECREMENT_QUANTITY="DECREMENT_QUANTITY";
